/**
 *This class consists a class handle to generate events 
 *generated by the object of class GuiConvertDml
 */
package sasco;


import java.awt.event.*;
import javax.swing.JOptionPane;
import java.util.StringTokenizer.*;
import java.io.*;
import java.util.*;
/**
 * This class handles event generated throgh its method
 * action performed. 
 * @author Pulkit Saxena
 * @implements ActonListener
 * @version 1.0
 * @Date 17 jun 07
 */
class GuiConvertDmlEvntHandler implements ActionListener {
	
	GuiConvertDml objGuiConvert;
	ArrayList listToken ;
	FileWriter writer;
	FileReader reader;
	
	/*
	 * Constructor for class
	 * @arg  object of class objGuiConvert
	 */ 
	public GuiConvertDmlEvntHandler(GuiConvertDml objGuiConvert){
		this.objGuiConvert = objGuiConvert;
		listToken= new ArrayList();
		JOptionPane.showMessageDialog ( objGuiConvert,new 
			 	  String("Enter DML in Sasco format" +"\n"+
			 	  		"for exapmle" +"\n"+
			 	  		"string(1)     goldcard_ind;"+"\n"+
  "string(1)     par_non_par_ind;"+"\n"+
  "decimal(20)   provider_id; "));  
	
	}
   
	/*
	 * This method handles event 
	 *  (non-Javadoc)
	 * @see java.awt.event.ActionListener#actionPerformed(java.awt.event.ActionEvent)
	 */
	public void actionPerformed(ActionEvent ae)
	{
	   String strTxtAreaDml;
	   String strToken;
	   String arg=(String)ae.getActionCommand();
	   if(arg.equals("Convert DML"))
	   {
		 strTxtAreaDml=objGuiConvert.txtAreaDml.getText();
	  
		 //this removes the extra new lines 
		 String str =strTxtAreaDml.trim();
		 
		 if(strTxtAreaDml.equals(""))
		   {
		   JOptionPane.showMessageDialog ( objGuiConvert,new 
		 	  String("Enter DML in Sasco format "));    
		       }
	 else
	 {
		   
		try {
			
			//writing dml to temporary file
			FileWriter writer = new FileWriter("temp.txt");
		//	writer.write(strTxtAreaDml);
			writer.write(str);
			writer.close();
			
			//reading from temporary file
			
			FileReader reader  = new FileReader("temp.txt");
			BufferedReader br =new BufferedReader(reader);
		    String s =" ";
			StringBuffer sb = new StringBuffer();
			
					
			
			//reading file
			while((s= br.readLine())!=null){
			//scanning for tokens 
	 java.util.StringTokenizer scan =
		new java.util.StringTokenizer(s," \t+()\t+;\n");
			    
		    //scanning started
			    while(scan.hasMoreTokens())
			     {   
	           	String trimmer =  scan.nextToken();
			    //removing any white spaces
	           	
	           	trimmer =trimmer.trim();
	 		   listToken.add(trimmer); 
				  }
			 
			    strToken = listToken.get(0).toString();
			    String checkToken=strToken.trim(); 
			   
			   String check="string";
			  
			   if(checkToken.equalsIgnoreCase( check))
			     {
			         
			      sb.append(listToken.get(2)+"  :$"+listToken.get(1)+".");
			       sb.append("\n");
			      }
			   else {
			     sb.append(listToken.get(2)+"  :"+listToken.get(1)+".");
			     sb.append("\n");
			    }  
			listToken.clear();   
			  }
	String pul =sb.toString();
     //displaying dml code created in text area
	objGuiConvert.txtAreaDml.setText(" ");
			objGuiConvert.txtAreaDml.setText(pul);
	//closing files
	reader.close();
    
	}
	catch(Exception e)
	        {
	     JOptionPane.showMessageDialog ( objGuiConvert,new 
		  String("DML  not in SASCO format ! ")); 	
          	 }
	File f1 = new File("temp.txt");
    boolean success = f1.delete();
	
	
	
	  }
		
		
   }
 }
 }
	

