/**
 * This java file consists a class to handle the 
 * window closing event generated by the object of
 * class  GuiConvertDmlFlatAdapter
 */
package sasco;
import java.awt.event.*;
/**
 *This class handles the window closingg event 
 * generated by the object of class GuiConvertDmlFlat
 * @author Pulkit Saxena
 * @version 1.0
 * Date 4-Jul-2007
 *
 */
public class GuiConvertDmlFlatAdapter extends WindowAdapter{
      
	GuiConverDmlFlat objGuiConvertDmlFlat;
	/**
	 * This constructor initialises the class 
	 * @param objGuiConvertDmlFlat
	 * object of GuiConverDmlFlat is passes as paramter 
	 * which created window closing event 
	 */
	public GuiConvertDmlFlatAdapter(GuiConverDmlFlat objGuiConvertDmlFlat) {
		
		// TODO object of class GuiConverDmlFlat passed
		this.objGuiConvertDmlFlat = objGuiConvertDmlFlat;
	
	}
	/**
	 * This method handles the window closing event 
	 * generated by the system
	 * @param we
	 */
	public void windowClosing(WindowEvent we)
	 {
		 objGuiConvertDmlFlat.setVisible(false);
	  }

	

}
