/**
 * This java file consists a class which handles the window 
 * closing event generated by the onject of GuiSasco
 */
package sasco;
import java.awt.event.*;
/**
 * This class handles the window closing event 
 * @author Pulkit Saxena
 * @version 1.0
 *
 */
public class GuiSascoAdapter extends WindowAdapter{
       GuiSasco objGuiSasco;
	
     /**
      * This constructor initialises the components
      * @param objGuiSasco
      */
       public GuiSascoAdapter(GuiSasco objGuiSasco) {
    	 this.objGuiSasco =objGuiSasco;
     }
       public void windowClosing(WindowEvent we)
	 {
		objGuiSasco.setVisible(false);
	  }
	
	
}
